# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: eilnn

on:
  push:
    branches:
  pull_request:
    branches:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  style:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        flake8

  build:
    needs: style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pybamm_pnm with dependencies
      run: |
        python -m pip install -e .
    - name: Run tests and generate coverage report
      run: |
        python -m pip install coverage
        coverage run -m unittest -v
